#%RAML 1.0
title: testShelf

/resourceName:
  get:
    #POINT 1
    responses:
      200:
        body:
          application/json:
            type: string
        headers:
          Content-Encoding:
            type: object
    #POINT 2
    #POINT 3
  #POINT 4
  #POINT 5
